config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get "/auth/google_oauth2/callback" => "sessions#create"
  get "log_out" => "sessions#destroy", :as => "log_out"

  root 'welcome#index'
  get 'welcome/home' => 'welcome#home', :as => 'home'

  post 'welcome/home' => 'welcome#change_date'
  get 'budget/expenses' => 'expenses#budget', :as => 'budget_expenses'
  get 'budget/revenues' => 'revenues#budget', :as => 'budget_revenues'

  resources :contributors do
  	resources :contributions
  end

  resources :expenses
  resources :periodic_expenses
  resources :expected_expenses
  resources :contribution_factors
  resources :revenues
  resources :categories
  resources :contributions
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_login, only: [:index]
    
  def index
    render layout: 'before_login' unless logged_in?
    redirect_to action: 'home' if logged_in?
  end

  def home
    now = DateTime.now
    budget_date = DateTime.new now.year, now.month, now.day, 0,0,0,"+00:00"
    load_values_for budget_date
  end

  def change_date
    budget_date = Date.new home_params["budget_date(1i)"].to_i, home_params["budget_date(2i)"].to_i, home_params["budget_date(3i)"].to_i
    load_values_for budget_date.to_datetime
    render 'home'
  end

  private

    def load_values_for budget_date
      @presenter = WelcomeHomePresenter.new budget_date: budget_date,
        revenues: Revenue.get_for_month(budget_date),
        expenses: Expense.get_expenses_same_month_of(budget_date),
        periodic_expenses: PeriodicExpense.get_expenses_for_month(budget_date),
        expected_expenses: ExpectedExpense.not_realized_on(budget_date),
        contributions: Contribution.get_contributions_for_month(budget_date),
        contribution_factor: ContributionFactor.find_for_month(budget_date)
    end

    def home_params
      params.require(:dashboard).permit(:budget_date)
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<% content_for :title do %>
    Bem vindo!
<% end %>

<div class="row">
  <div class="col-sm-4">
    <%= form_for :dashboard, id: "chage_date", url: {action: "change_date"} do |f| %>
        <div>
          <div>
            <%= date_select "dashboard", "budget_date", default: @presenter.budget_date, order: [:month, :year] %>
          </div>
          <div>
            <input class="btn btn-primary" name="commit" type="submit" value="Go!">
            <input class="btn btn-secondary" name="commit" type="submit" value="Today" formmethod="get">
          </div>
        </div>
    <% end %>
  </div>
  <div class="col-sm-4">
    <table>
      <thead>
      <tr>
        <th colspan="2"><%= @presenter.formated_budget_date %></th>
      </tr>
      </thead>
      <tfoot>
      <tr>
        <td>Saldo</td>
        <td><%= @presenter.balance %></td>
      </tr>
      </tfoot>
      <tbody>
      <tr>
        <td><%= link_to 'Contribuições', contributions_path(budget_date: @presenter.budget_date), method: :get %></td>
        <td><%= @presenter.total_contributions %></td>
      </tr>
      <tr>
        <td><%= link_to 'Receitas', budget_revenues_path(budget_date: @presenter.budget_date), method: :get %></td>
        <td><%= @presenter.total_revenues %></td>
      </tr>
      <tr>
        <td><%= link_to 'Despesas', budget_expenses_path(budget_date: @presenter.budget_date), method: :get %></td>
        <td><%= @presenter.total_expenses %></td>
      </tr>
      </tbody>
    </table>
  </div>
  <div class="col-sm-4">
    <div id="chart_div"></div>
  </div>
</div>

<div class="row" style="margin-top: 20px">
  <div class="col-sm-4 offset-sm-4">
    <a href="http://thecatapi.com"><img src="http://thecatapi.com/api/images/get?format=src&type=png&size=small"></a>
  </div>
</div>
<script type="text/javascript">
  google.load('visualization', '1.0', {'packages': ['corechart']});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Categoria');
    data.addColumn('number', 'Soma');
    data.addRows([
      <% @presenter.categories.each_key do |key| %>
      ['<%= key %>', <%= @presenter.categories[key] %>],
      <% end %>
    ]);

    var options = {
      'title': 'Despesas por categoria', colors: [
        <% @presenter.colors.each do | color |%>
        '<%= color %>',
        <% end %>
      ]
    };

    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>

app/views/welcome/index.html.erb
<a href="http://thecatapi.com"><img src="http://thecatapi.com/api/images/get?format=src&type=png&size=small"></a>