config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get "/auth/google_oauth2/callback" => "sessions#create"
  get "log_out" => "sessions#destroy", :as => "log_out"

  root 'welcome#index'
  get 'welcome/home' => 'welcome#home', :as => 'home'

  post 'welcome/home' => 'welcome#change_date'
  get 'budget/expenses' => 'expenses#budget', :as => 'budget_expenses'
  get 'budget/revenues' => 'revenues#budget', :as => 'budget_revenues'

  resources :contributors do
  	resources :contributions
  end

  resources :expenses
  resources :periodic_expenses
  resources :expected_expenses
  resources :contribution_factors
  resources :revenues
  resources :categories
  resources :contributions
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :contributor
  validates :budget_date, :amount, presence: true
  validate :same_month_same_contributor

  def self.get_contributions_for_month(date)
    last_month_day = date.utc.end_of_month
    Contribution.select("DISTINCT ON (contributor_id) amount as amount, contributor_id as contributor_id, budget_date as budget_date, id as id")
                .where(["budget_date <= ?", last_month_day])
                .order(contributor_id: :asc, budget_date: :desc).to_a
  end

  private
  def same_month_same_contributor
    if self.budget_date and self.contributor
      self.budget_date = self.budget_date.midnight
    	first_month_day = self.budget_date.beginning_of_month
    	last_month_day = self.budget_date.end_of_month
    	if new_record? && Contribution.where(:contributor_id => self.contributor.id)
                     .where(:budget_date => first_month_day..last_month_day).any?
    		errors.add(:budget_date, "can't be two in the same month")
    	end
    end
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController

	def index
		budget_date = DateTime.parse(params[:budget_date] || DateTime.now.utc.to_s)
		@contributions = Contribution.get_contributions_for_month(budget_date)
	end
	
	def create
		@contributor = Contributor.find(params[:contributor_id])
    @contribution = @contributor.contributions.create(strong_params)
    redirect_to contributor_path(@contributor)
	end

	def edit
		@contribution = Contribution.find(params[:id])
		@contributor = Contributor.find(@contribution.contributor_id)
	end

	def update
	    @contribution = Contribution.find(params[:id])
	    @contributor = Contributor.find(@contribution.contributor_id)
	    if @contribution.update(strong_params)
	      redirect_to @contributor
	    else
	      render 'edit'
	    end
	end	

	def destroy
		@contribution = Contribution.find(params[:id])
		@contribution.destroy

		redirect_to contributors_path
	end

	private
    def strong_params
			params.require(:contribution).permit(:amount, :budget_date)
    end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/edit.html.erb
<%= form_for :contribution, url: contributor_contribution_path(@contributor, @contribution), method: :patch do |f| %>
  <% if @contribution.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@contribution.errors.count, "error") %> prohibited
      this contribution from being saved:</h2>
    <ul>
    <% @contribution.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="row">
    <div class="small-2 columns">
      <%= f.label :amount, class: "right inline" %>
    </div>
    <div class="small-5 columns end">
      <%= f.text_field :amount %>
    </div>
  </div>
  <div class="row">
    <div class="small-2 columns">
      <%= f.label :budget_date, "Budget", class: "right inline" %>
    </div>
    <div class="small-3 columns end">
      <%= date_select "contribution", "budget_date", order: [:month, :year] %>
    </div>
  </div>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', contributor_contributions_path %>

app/views/contributions/index.html.erb
<table class="table table-striped">
  <tr>
    <th>Contribuidor</th>
    <th>Valor</th>
    <th>Desde</th>
  </tr>
 
  <% @contributions.each do |contribution| %>
    <tr>
      <td><%= contribution.contributor.full_name %></td>
      <td><%= contribution.amount %></td>
      <td><%= contribution.budget_date.strftime("%B %Y") %></td>
      <td><%= link_to 'Edit', edit_contribution_path(contribution) %></td>
      <td><%= link_to 'Destroy', contribution_path(contribution), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>