config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get "/auth/google_oauth2/callback" => "sessions#create"
  get "log_out" => "sessions#destroy", :as => "log_out"

  root 'welcome#index'
  get 'welcome/home' => 'welcome#home', :as => 'home'

  post 'welcome/home' => 'welcome#change_date'
  get 'budget/expenses' => 'expenses#budget', :as => 'budget_expenses'
  get 'budget/revenues' => 'revenues#budget', :as => 'budget_revenues'

  resources :contributors do
  	resources :contributions
  end

  resources :expenses
  resources :periodic_expenses
  resources :expected_expenses
  resources :contribution_factors
  resources :revenues
  resources :categories
  resources :contributions
end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
	has_many :contributions, dependent: :destroy
	has_many :expenses
	validates :firstName, :lastName, presence: true, length: { minimum: 1 }
	validates :email, presence: true, confirmation: true, uniqueness: { case_sensitive: false }

	def full_name
		self.firstName + " " + self.lastName
	end
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController

	def index
		@contributors = Contributor.all
	end

	def new
		@contributor = Contributor.new() unless @contributor
	end

	def create
		@contributor = Contributor.new(contributor_create_params)
		if @contributor.save
			redirect_to @contributor
		else
			render 'new'
		end
	end

	def show
		@contributor = Contributor.find(params[:id])
		@contribution = Contribution.new unless @contribution
	end

	def edit
		@contributor = Contributor.find(params[:id])
	end

	def update
		@contributor = Contributor.find(params[:id])
		if @contributor.update(contributor_update_params)
			redirect_to @contributor
		else
			render 'edit'
		end
	end

	def destroy
		@contributor = Contributor.find(params[:id])
		@contributor.destroy
		
		redirect_to contributors_path
	end
	private
		def contributor_create_params
			params.require(:contributor).permit(:firstName, :lastName, :email, :email_confirmation)
		end

		def contributor_update_params
			params.require(:contributor).permit(:firstName, :lastName)
		end
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/views/contributors/edit.html.erb
<h1>Editing contributor</h1>
 
<%= form_for :contributor, url: contributor_path(@contributor), method: :patch do |f| %>
  <% if @contributor.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@contributor.errors.count, "error") %> prohibited
      this contributor from being saved:</h2>
    <ul>
    <% @contributor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </p>
 
  <p>
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', contributors_path %>

app/views/contributors/index.html.erb
<h1>Listing contributors</h1>
<%= link_to 'New contributor', new_contributor_path, class: "button tiny" %>
<table class="table table-striped">
  <tr>
    <th></th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
 
  <% @contributors.each do |contributor| %>
    <tr>
      <td><%= contributor.id %></td>
      <td><%= contributor.firstName %></td>
      <td><%= contributor.lastName %></td>
      <td><%= contributor.email %></td>
      <td><%= link_to 'Show', contributor_path(contributor) %></td>
      <td><%= link_to 'Edit', edit_contributor_path(contributor) %></td>
      <td><%= link_to 'Destroy', contributor_path(contributor), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/contributors/new.html.erb
<h3>New Contributor</h3>
<%= form_for :contributor, url: contributors_path do |f| %>
    <% if @contributor.errors.any? %>
          
        <div id="error_explanation">
              <h2><%= pluralize(@contributor.errors.count, "error") %> prohibited
                this contributor from being saved:</h2>
              
          <ul>
                
            <% @contributor.errors.full_messages.each do |msg| %>
                      
                <li><%= msg %></li>
                    
            <% end %>
                
          </ul>
            
        </div>
          
    <% end %>
    <div>
      <%= f.label :firstName, class: "right inline" %>
      <%= f.text_field :firstName %>
    </div>
    <div>
      <%= f.label :lastName, class: "right inline" %>
      <%= f.text_field :lastName %>
    </div>
    <div>
      <%= f.label :email, class: "right inline" %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :email_confirmation, class: "right inline" %>
      <%= f.text_field :email_confirmation %>
    </div>
    <div>
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', contributors_path %>

app/views/contributors/show.html.erb
<p>
  <strong>Contributor:</strong>
  <%= @contributor.firstName + " " + @contributor.lastName %> (<%= @contributor.email %>)
</p>

<% if @contributor.contributions.any? %>
  <table>
    <tr>
      <th>Value</th>
      <th>Since</th>
      <th colspan="2"></th>
    </tr>
   
    <% @contributor.contributions.order(:budget_date).each do |contribution| %>
      <tr>
        <td><%= contribution.amount %></td>
        <td><%= contribution.budget_date.strftime("%B %Y") %></td>
        <td><%= link_to 'Edit', edit_contributor_contribution_path(contribution.contributor, contribution) %></td>
        <td><%= link_to 'Destroy', contributor_contribution_path(contribution.contributor, contribution), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<h5>Add a contribution</h5>
<%= form_for([@contributor, @contributor.contributions.build]) do |f| %>
  <% if @contribution.errors.count > 0 %>
  <div id="error_explanation">
    <h2><%= pluralize(@contribution.errors.count, "error") %> ao salvar:</h2>
    <ul>
    <% @contribution.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="row">
    <div class="small-2 columns">
      <%= f.label :budget_date, "Initial date:" %>
    </div>
    <div class="small-4 columns end">
      <%= date_select "contribution", "budget_date", order: [:month, :year], prompt: { month: 'Select month', year: 'Select year' } %>
    </div>
  </div>
  <div class="row">
    <div class="small-2 columns">
      <%= f.label :amount, "Value" %>
    </div>
    <div class="small-1 columns">
      <%= f.label :amount, "R$", class: "prefix" %>
    </div>
    <div class="small-4 columns end">
      <%= f.text_field :amount %>
    </div>
  </div>
  <div class="row">
    <%= f.submit "Save", class: "button tiny" %>
  </div>
<% end %>

<%= link_to 'Back', contributors_path, class: "button tiny" %> |
<%= link_to 'Edit', edit_contributor_path(@contributor), class: "button tiny" %>