config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get "/auth/google_oauth2/callback" => "sessions#create"
  get "log_out" => "sessions#destroy", :as => "log_out"

  root 'welcome#index'
  get 'welcome/home' => 'welcome#home', :as => 'home'

  post 'welcome/home' => 'welcome#change_date'
  get 'budget/expenses' => 'expenses#budget', :as => 'budget_expenses'
  get 'budget/revenues' => 'revenues#budget', :as => 'budget_revenues'

  resources :contributors do
  	resources :contributions
  end

  resources :expenses
  resources :periodic_expenses
  resources :expected_expenses
  resources :contribution_factors
  resources :revenues
  resources :categories
  resources :contributions
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) + " - Budget on rails" : "Budget on rails" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
</head>

<body>
<nav class="navbar navbar-fixed-top navbar-dark bg-primary">
  <%= link_to 'Início', home_url, class: 'navbar-brand' %>
  <ul class="nav navbar-nav">
    <li class="nav-item dropdown">
      <%= link_to 'Despesas', expenses_path, {id: 'expenses', class: 'nav-link dropdown-toggle', data: {toggle: 'dropdown'}, aria_haspopup: 'true', aria_expanded: 'false'} %>
      <div class="dropdown-menu" aria-labelledby="expenses">
        <%= link_to "Única", expenses_path, class: 'dropdown-item' %>
        <%= link_to "Por período", periodic_expenses_path, class: 'dropdown-item' %>
        <%= link_to "Planejada", expected_expenses_path, class: 'dropdown-item' %>
      </div>
    </li>
    <li class="nav-item dropdown">
      <%= link_to 'Receitas', revenues_path, {id: 'revenue', class: 'nav-link dropdown-toggle', data: {toggle: 'dropdown'}, aria_haspopup: 'true', aria_expanded: 'false'} %>
      <div class="dropdown-menu" aria-labelledby="revenue">
        <%= link_to "Nova", new_revenue_path, class: 'dropdown-item' %>
        <%= link_to "Listar", revenues_path, class: 'dropdown-item' %>
      </div>
    </li>
    <li class="nav-item dropdown">
      <%= link_to "Categoria", categories_path, {class: 'nav-link dropdown-toggle', data: {toggle: 'dropdown'}, aria_haspopup: 'true', aria_expanded: 'false'} %>
      <div class="dropdown-menu" aria-labelledby="revenue">
        <%= link_to "Nova", new_category_path, class: 'dropdown-item' %>
        <%= link_to "Listar", categories_path, class: 'dropdown-item' %>
      </div>
    </li>
    <li class="nav-item">
      <%= link_to "Fator de contribuição", contribution_factors_path, class: "nav-link" %>
    </li>
  </ul>
  <div class="form-inline float-xs-right">
    <ul class="nav navbar-nav">
      <% if current_user %>
          <li class="nav-item float-lg-right">
            <%= link_to "Sair", log_out_path, class: "nav-link" %>
          </li>
          <li class="nav-item float-lg-right">
            <%= link_to image_tag("#{user_image}", size: "30x30"), {:id => current_user.id, :action => 'show', :controller => 'contributors'}, class: "nav-link" %>
          </li>
      <% else %>
          <li class="nav-item float-lg-right"><%= link_to 'Entrar', '/auth/google_oauth2', class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>
<div class="container-fluid">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
  <% end %>
  <%= yield %>
</div>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/before_login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>

  <!-- Uncomment to make IE8 render like IE7 -->
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<nav class="navbar navbar-fixed-top navbar-dark bg-primary">
  <%= link_to 'Início', home_url, class: 'navbar-brand' %>
  <div class="float-xs-right">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Login', '/auth/google_oauth2', class: "nav-link" %></li>
    </ul>
  </div>
</nav>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
<% end %>

<div class="container-fluid">
  <%= yield %>
</div>

<%= javascript_include_tag "application" %>
</body>
</html>